version: "3"
services:
    db:
        build: ./database
        environment:
            SA_PASSWORD: "SQLSERVER_password9!"
            ACCEPT_EULA: "Y"
    webapi:
        build: ./src/TodoList.WebApi
        environment:
            ConnectionStrings__SqlServerConnection: "Server=db;Database=TodoList;User=sa;Password=SQLSERVER_password9!;"
            JwtToken__Audience: "TodoClient"
            JwtToken__Issuer: "TodoApi"
            JwtToken__Key: "VjFod1MxWXlSblJVYmxKWFlXcz0"
            JwtToken__Seconds: 180
        ports:
            - "5000:80"
        depends_on:
            - db
